### PR TITLE
TypeScript Support

### LINKED ISSUE #150: TypeScript Support
I'm looking to use this library within our TypeScript project, and type definitions would be super useful. Is anything like this on the cards? If not, I'd be willing to submit a PR.

### PR DESCRIPTION
**Pull request by sharkBiscuit**
Hi, here some Typescript definitions for redux-saga-test-plan.

I saw #156 but found those types not sufficiently detailed and they had issues as mentioned in the PR.

I tested this types with 400 of your test cases (copied them in my ts project and renamed js => ts). 
Luckily, flow and typescript are extremely similar so I could run them w/o too much hassle.
As far as I can see, these types are "fairly complete".

Closes #150

### CODE REVIEW

**Comment by jfairbank** [comment]
Sorry for the delay, @sharkBiscuit. Thanks for the PR!

**Comment by paulsturgess** [comment]
Great work on this but unfortunately I don't think it is working... I have `3.4.0` but VS Code is saying:
`Could not find a declaration file for module 'redux-saga-test-plan'.`

Maybe I'm missing something, but I can't see the various `*.d.ts` files in the bundle. I think it's because `files` in `package.json` doesn't list them.

**Comment by jfairbank** [comment]
Thanks for the heads up @paulsturgess. I've included `*.d.ts` in the `files` property in the latest release.

**Comment by paulsturgess** [comment]
Thanks @jfairbank just downloaded `3.4.1` and it works great 👍

**Pull request merged**
