### PR TITLE
Add typescript type definitions

### LINKED ISSUE #150: TypeScript Support
I'm looking to use this library within our TypeScript project, and type definitions would be super useful. Is anything like this on the cards? If not, I'd be willing to submit a PR.

### PR DESCRIPTION
**Pull request by kennethlynne**
This allows consumers to use this package with strong typing. Closes #150

### CODE REVIEW

**Comment by jfairbank** [comment]
Thanks for the PR @kennethlynne!

This looks good to me, except it would be nice to support `expectSaga` as well. Would you be willing to add typings for it please?

Also, since I'm not terribly familiar with including typescript in packages would anyone else mind helping review this PR?

**Comment by kennethlynne** [comment]
Will do @jfairbank

**Comment by kennethlynne** [comment]
@jfairbank added!

**Comment by jfairbank** [comment]
Thanks for the update and sorry for the delay! I think this is really close, but it looks like some things are missing in both interfaces. You'll want to ensure the interfaces are similar to the types defined in the `decls/index.js` file for Flow.

For `testSaga`, you'll need two interfaces like this I believe: https://github.com/jfairbank/redux-saga-test-plan/blob/master/decls/index.js#L4-L44. Note that the assertions (e.g. `put`, `call`, etc.) are only available from calling `next`, `finish`, and `throw`. Also note that `parallel` is replaced with `all`.

For `expectSaga`, you'll need to mimic this type: https://github.com/jfairbank/redux-saga-test-plan/blob/master/decls/index.js#L239-L258. You're mostly there, I just noticed some methods were still missing in the TypeScript interface.

Thanks again for working on this!

**Comment by jfairbank** [comment]
Closed in favor of #159

**Pull request closed without merging**
