### PR TITLE
Upgrade to Babel 7

### PR DESCRIPTION
**Pull request by mike1808**
I was trying to add debug and add a new feature and the breakpoint was not working, turns out it was a bug in Jest, however, in order to fix that I needed to upgrade the Jest, so I ended up upgrading Babel to v7. As v6 is deprecated and its support will go down soon this upgrade is inevitable.

### CODE REVIEW

**Comment by mike1808** [comment]
One thing that might be broken is support for Node.js < 9

**Comment by mike1808** [comment]
@jp928 is the support for Node.js < 8 required for this project? All tools in the JS ecosystem are dropping support for them (like Webpack, Babel, Jest) and moving forward. Do you want to reconsider that?

**Comment by jp928** [comment]
@mike1808 
I agree with you and I had open a discussion on this. Please fix the conflicts and I will merge

**Comment by jp928** [comment]
@mike1808  Thanks for you PR. I had pick the updates except the conflict file.

**Pull request closed without merging**
