### PR TITLE
Immutable.js support

### PR DESCRIPTION
**Pull request by peleteiro**
When testing my sagas that return Immutable.js values, it seems not to work. I suggest checking if the object has .equals method then use it for equality check.

It seems to work if all objects in the list are created strict equal, with the keys in the same order. I changed key order on 'Chocolate Cake' creation to make sure they are not created in the same way.

Eg:
``cake.js``
```javascript
import {List, Record} from 'immutable'
import {put} from 'redux-saga/effects'

export class Cake extends Record({
  id: null,
  name: null,
}, 'Cake') {}

export function * bakeCakesSaga() {
  const cakesToBake = List([
    new Cake({id: 'orange', name: 'Orange Cake'}),
    new Cake({name: 'Super Chocolate Cake', id: 'supchocolate'}),
  ])
  yield put({type: 'BAKE_CAKES', cakesToBake})
}
```

``cake.test.js``
```javascript
/* eslint-disable padded-blocks */
import {List} from 'immutable'
import {expectSaga} from 'redux-saga-test-plan'
import {Cake, bakeCakesSaga} from './cake'

describe('bakeCakesSaga', () => {

  test('weird equality', () => { // IT WORKS
    const c1 = new Cake({id: 'supchocolate', name: 'Super Chocolate Cake'})
    const c2 = new Cake({name: 'Super Chocolate Cake', id: 'supchocolate'})

    expect(c1).toEqual(c2)
    expect(List([c1])).toEqual(List([c2]))
  })

  test('puts an BAKE_CAKES action', () => { // IT DOESN'T
    const cakesToBake = List([
      new Cake({id: 'orange', name: 'Orange Cake'}),
      new Cake({id: 'supchocolate', name: 'Super Chocolate Cake'}),
    ])

    return expectSaga(bakeCakesSaga)
      .put({type: 'BAKE_CAKES', cakesToBake})
      .run()
  })
})
```

Thanks

### CODE REVIEW

**Comment by peleteiro** [comment]
I added support to objects that have an equals method using Lodash's isEqualWith customizer function.

I also removed Lodash.isequal from package.json for Lodash.isequalwith and added immutable.js as a development dependency to use it on a test case.

What do you think?

**Comment by peleteiro** [comment]
Any word on this PR?

**Comment by jfairbank** [comment]
Hey, @peleteiro.

Apologies, but I've been busy with bug fixes as well as other responsibilities. I appreciate your taking the time to investigate and make a PR.

However, per our earlier conversation, I'm not in favor of internally checking for an `equals` method and can't accept this PR as is. I don't consider an `equals` method to be a standard, and don't want this library to assume that it's safe to invoke an `equals` method if it finds it. This either has to be an opt-in behavior via my earlier recommendation `compareWith` or a more general solution similar to how Jest's `toEqual` works with iterable objects [here](https://github.com/facebook/jest/blob/10e492754fd9f2f0280c625f15800fb8f3347558/packages/jest-matchers/src/matchers.js#L47-L73). Mimicking what Jest does might be the best approach, which avoids adding another method to the `expectSaga` API.

If you update this PR to take that general approach, I will definitely consider merging. Thanks!

**Comment by peleteiro** [comment]
Ok, thanks.

**Pull request closed without merging**
